# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Codacy Analysis CLI
      # You may pin to the exact commit or the version.
      # uses: codacy/codacy-analysis-cli-action@0de770495bd94bdac1ba7d5043a72b252ddbeec3
      uses: codacy/codacy-analysis-cli-action@4.0.0
      with:
        # Run with verbose output
        verbose: # optional
        # API project token to retrieve your remote Codacy configuration for the project being analyzed
        project-token: # optional
        # API account token to retrieve your remote Codacy configuration for the project being analyzed
        api-token: # optional
        # Codacy's API URL, to retrieve your remote Codacy configuration
        codacy-api-base-url: # optional
        # Format of the output file
        format: # optional
        # Send analysis results to an output file
        output: # optional
        # The directory to be analyzed
        directory: # optional
        # Number of tools to run in parallel
        parallel: # optional
        # Maximum number of issues allowed for the analysis to succeed
        max-allowed-issues: # optional, default is 2147483647
        # The name of the tool to analyze the code
        tool: # optional
        # Maximum time each tool has to execute
        tool-timeout: # optional
        # Upload analysis results to Codacy
        upload: # optional
        # Fail the analysis if any tool fails to run
        fail-if-incomplete: # optional
        # Allow network access for tools
        allow-network: # optional
        # Force files to be readable by changing the permissions before running the analysis
        force-file-permissions: # optional
        # Reduce issue severity by one level, for non-security issues, for compatibility with GitHub's code scanning feature. This option will only have an effect when used in conjunction with '--format sarif'.
        gh-code-scanning-compat: # optional
        # Run dockerized tools. Possible values (true|false) Check the full list in https://docs.codacy.com/repositories-configure/codacy-configuration-file/#which-tools-can-be-configured-and-which-name-should-i-use
        run-docker-tools: # optional, default is true
        # Run GoSec. Possible values (true|false)
        run-gosec: # optional
        # Run StaticCheck. Possible values (true|false)
        run-staticcheck: # optional
        # Path to a file containing the output of Clang Tidy.
        clang-tidy-output: # optional
        # Path to a file containing the output of Faux Pas.
        faux-pas-output: # optional

      - name: SonarCloud Scan
      # You may pin to the exact commit or the version.
      # uses: SonarSource/sonarcloud-github-action@de2e56b42aa84d0b1c5b622644ac17e505c9a049
      uses: SonarSource/sonarcloud-github-action@v1.6
      with:
        # Additional arguments to the sonarcloud scanner
        args: # optional
        # Set the sonar.projectBaseDir analysis property
        projectBaseDir: # optional, default is .
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
